# Generated by Django 5.0.7 on 2024-10-11 06:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DressOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordtitle', models.CharField(default='', max_length=50, verbose_name='Order Title')),
                ('user', models.CharField(max_length=30, verbose_name='Username')),
                ('useremail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Client Email')),
                ('usercontact', models.IntegerField(blank=True, null=True, verbose_name='Client Ph.No')),
                ('userfullname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Client Full Name')),
                ('tailor', models.CharField(max_length=30, verbose_name='Tailor Username')),
                ('tailoremail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Tailor Email')),
                ('tailorcontact', models.IntegerField(blank=True, null=True, verbose_name='Tailor Ph.No')),
                ('tailorfullname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tailor Full Name')),
                ('body_size', models.CharField(max_length=20, verbose_name='Body Size')),
                ('cloth_type', models.CharField(max_length=30, verbose_name='Cloth Type')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Budget')),
                ('color', models.CharField(max_length=15, verbose_name='Preferred Color')),
                ('design_reference', models.ImageField(blank=True, null=True, upload_to='design_references/', verbose_name='Design Reference Image')),
                ('additional_notes', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('orderstatus', models.CharField(choices=[('undecided', 'Undecided'), ('pending', 'Accepted'), ('declined', 'Declined'), ('pending', 'Pending'), ('completed', 'Completed')], default='undecided', max_length=10, verbose_name='Order Status')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('client', 'Client'), ('tailor', 'Tailor')], max_length=10)),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('experience', models.PositiveIntegerField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=20, null=True)),
                ('ratings', models.IntegerField(blank=True, default=0, null=True)),
                ('biodis', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.IntegerField()),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='customuser_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
