# Generated by Django 5.0.7 on 2024-10-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contact',
            field=models.BigIntegerField(),
        ),
    ]
