# Generated by Django 5.0.7 on 2024-10-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_alter_customuser_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contact',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
