# Generated by Django 5.0.7 on 2024-10-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0005_rename_location_customuser_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dressorder',
            name='clientaddcity',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='dressorder',
            name='clientaddress',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dressorder',
            name='clientaddstate',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='dressorder',
            name='clientaddzipcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
