# Generated by Django 5.0.7 on 2024-10-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0006_dressorder_clientaddcity_dressorder_clientaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dressorder',
            name='deliverydate',
            field=models.DateField(blank=True, null=True, verbose_name='Expected Delivery'),
        ),
        migrations.AddField(
            model_name='dressorder',
            name='deliveryinfo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dressorder',
            name='deliverypatner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
